CREATE TABLE `tasks` (
  `id`          BIGINT                AUTO_INCREMENT,
  `body`        VARCHAR(255) NOT NULL,
  `status`      VARCHAR(10),
  `deadline`    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `complete_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_at`   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at`   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
